### ISSUE TITLE
Proxy Support Options? Dummy Run output?

### ISSUE THREAD

**Issue by GitStoph** [Tib3rius/AutoRecon#106]
Scenario:
Trying to scan a target through a pivot in the lab. 

Issue: 
sshuttle causes nmap to think *everything* is open. 
proxychains causes nmap to be slow as heck. 

The manual commands that get spit out after a scan is great. If there was a way to switch from proxychains to sshuttle after the nmap scan was done that'd be stellar. Or even just spit out a list of commands to do later? Just spitballing ideas here. 

Thanks for the great tool!

**Comment by Tib3rius** [comment]
Can you share the command you ran? Did you use --proxychains?

**Comment by GitStoph** [comment]
sudo proxychains python3 autorecon.py -o ~/Labs/10.1.1.65/ -v --proxychains --single-target --dirbuster.tool feroxbuster -p 21,25,80,135,139,445,2021,2110,3389,5040,7680 10.1.1.65

Sorry. been hitting the books hard and not checking personal email. Been getting frustrated with pivots and inconsistent shell return when i find a vuln so i moved back to the public lab until that's cleaned out.

**Comment by MalwareExploit** [comment]
If you're going to do that, I would highly recommend just uploading a nmap binary to the vulnerable box and use that box for your nmap enumeration.

**Comment by Tib3rius** [comment]
@GitStoph unfortunately there's no easy way to make pivoting with AutoRecon easy, since it uses so many different programs. --proxychains effectively converts all nmap scans to use -sT which *should* make them compatible with SOCKS proxies.

Out of interest, how does sshuttle work in order to do pivoting? I can try a few things if I know how it works. I can also potentially try to make it so you can disable the actual running of service scan commands, but print them out for manual use.
