### ISSUE TITLE
When you specify multiple dirbusting wordlists, then are only unique entries used?

### ISSUE THREAD

**Issue by heinosasshallik** [Tib3rius/AutoRecon#124]
When you specify multiple dirbusting wordlists, then are only unique entries used? 

If not, then that's pretty inefficient. It would be a good idea to only use unique entries. Otherwise, the scan times will get unnecessarily long when using multiple wordlists that may overlap (for example the default SecLists wordlists)

If yes, then that should be mentioned in the readme. That's a pretty important detail.

**Comment by Tib3rius** [comment]
Hi @heinosasshallik,

Unique entries are not used since the directory busting tool is simply run with each wordlist separately. I agree that it is inefficient, but the alternative was potentially missing directories. The advantage is that shorter wordlists are run first, meaning you get results you can look at faster. You can of course change this behavior by overriding the default options in either the config file or on the command line.

I think the best solution though is to create a merged unique wordlist and ship that with AutoRecon itself.

**Comment by heinosasshallik** [comment]
@Tib3rius I've already created an [universal merged wordlist](https://github.com/heinosasshallik/infosec-knowledge/tree/master/wordlists/web_content) that you can use if you want to.

I've also created an issue in SecLists to include the universal wordlist there (either automatically via github pipelines or just manually as a file), which you can support here: https://github.com/danielmiessler/SecLists/issues/652#issuecomment-963304989

**Comment by Tib3rius** [comment]
Fixed in 43954a3.
