### ISSUE TITLE
Vote: Keep dirb as the default directory buster, or force people to upgrade to gobuster v3?

### ISSUE THREAD

**Issue by Tib3rius** [Tib3rius/AutoRecon#20]
There's no easy way to do feature voting on GitHub (to my knowledge), so this will be a comment poll. One vote per person.

Since gobuster v3 is not backwards compatible with gobuster v2, and the OffSec Kali VM by default comes with gobuster v2, AutoRecon's default directory buster was changed to dirb to avoid instances where AutoRecon was trying to use the wrong gobuster syntax.

dirb is good, but it's not as good as gobuster. Hence, this poll which will ultimately decide whether AutoRecon should require people to install / upgrade gobuster v3.

Vote by stating either **dirb** or **gobuster**. If you want to leave a comment / argument, please make your vote clear (e.g. by using bold text).

**Comment by cmsteffen-code** [comment]
**dirb** has been my go-to lately. It gets the job done.

**Comment by cam-barts** [comment]
I have found gobuster so much faster than dirb.  The only con about it that I have found is that it doesn't recursively check found directories. If I have to choose one, I would choose gobusterV3. But why not build in some logic that either checks if gobuster is installed, and reverts to running dirb if not, or else just let the user decide with a flag?

**Comment by michelangelo-sarafis** [comment]
Even though myself I have proposed dirb as a solution when this issue was first raised, I now believe that GoBuster is probably the way to go. The reason is that GoBuster:

- GoBuster does not list recursively (something that saves time)
- GoBuster seems to be faster (a time difference of a minute or so than dirb).
- GoBuster does not have an issue with self-signed SSL certificates (**VERY IMPORTANT**).

Now of course the issue is backwards compatibility, therefore (as @cam-barts said) I believe it would be a good idea for AutoRecon to check if GoBuster is installed, and if yes, to use it. Otherwise it should mention it to the user and move on using dirb.

**Comment by perfectra1n** [comment]
GoBuster seems to give me much better luck, and runs faster.

**Comment by BrashEndeavours** [comment]
+1 for gobuster

**Comment by ah8r** [comment]
Thanks for the votes. As of c46cb86ec6d1909b85c94c6fbbcc51977cdc224f, gobuster is the default directory enumeration tool, and there is also some very simple code that tries to run the correct version too.

**Comment by Tib3rius** [comment]
Thanks for the votes. As of c46cb86, gobuster is the default directory enumeration tool, and there is also some very simple code that tries to run the correct version too.
