### ISSUE TITLE
Trouble getting heartbeat to work

### ISSUE THREAD

**Issue by jordonposey** [Tib3rius/AutoRecon#220]
Hello! I have been trying to lower the heartbeat timer to 30 seconds, but I don't get any heartbeat notification at all (even at the default 60 seconds) when running the following command. I use this command to run as root so the SYN scan will work properly (as stated in documentation).

`sudo env "PATH=$PATH" autorecon --heartbeat 30 [target_ip]`

I am running Kali x64 in VMware.

Thank you.

**Comment by Tib3rius** [comment]
Are you running the latest version? I *think* this was caused by an exception which would effectively prevent the heartbeat from printing anything: https://github.com/Tib3rius/AutoRecon/issues/217

This got patched in 2.0.35. If I run your example command in 2.0.34 I don't get the heartbeat either, but in 2.0.35 it works fine. Can you upgrade and check?

**Comment by jordonposey** [comment]
Upgrading fixed it. Thank you for fixing my broken heart!
