### ISSUE TITLE
Task tcp/443/gobuster on 10.11.1.123 returned non-zero exit code: 1

### ISSUE THREAD

**Issue by u-ahmedofficial** [Tib3rius/AutoRecon#69]
Hi Tib3rius,

First of all thank you so much for such an awesome tool. The problem here is in "service-scans-default.toml" in the configs, you have used "`gobuster -h 2>&1 | grep -F "mode (dir)"`" , this will grep for string "mode (dir)" however in the  later version of gobuster, their is no such text hence it does not get executed as expected.

update this to: `gobuster -h 2>&1 | grep -F "dir"

![Screenshot from 2020-12-18 05-57-17](https://user-images.githubusercontent.com/42877060/102561215-f5352c80-40f5-11eb-9e2d-331d4cd73cad.png)
` 
Thanks

**Comment by CybertSys** [comment]
I'm having issues with this as well. I tried your suggestion but it is still failing.

**Comment by robsware** [comment]
> I'm having issues with this as well. I tried your suggestion but it is still failing.

Autorecon creats a config file in ~/.config after the first run. If you run autorecon as root, that config file is in /root/.config/AutoRecon . Otherwise it's in /home/kali/.config/AutoRecon . Delete the .toml files there and edit the default config file in your original Autorecon directory (i.e. /opt/AutoRecon/src/autorecon/config) according to the first post. When you run Autorecon again, gobuster should work. 

I've forked the repo and fixed the gobuster issue, you can find it on my profile. You'll still have to clear your .config files.

**Comment by fbi4gent** [comment]
The issue seems to be with `-l` option in `gobuster` which was replaced with `--hide-length`.
See `gobuster help dir`.

**Comment by guyrtho** [comment]
I have updated the service-scans-default.toml with the revision - still seems to be failling.  This fix does not repair.

**Comment by Tib3rius** [comment]
Fixed in fb9ca7e
